# Generated by Django 5.0.2 on 2024-02-07 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 7, 18, 33, 42, 965424)),
        ),
    ]
